/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SenseMsg'
 * message type.
 */

public class SenseMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 3;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new SenseMsg of size 3. */
    public SenseMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SenseMsg of the given data_length. */
    public SenseMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg with the given data_length
     * and base offset.
     */
    public SenseMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg using the given byte array
     * as backing store.
     */
    public SenseMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SenseMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SenseMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg embedded in the given message
     * at the given base offset.
     */
    public SenseMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SenseMsg embedded in the given message
     * at the given base offset and length.
     */
    public SenseMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SenseMsg> \n";
      try {
        s += "  [cnt=0x"+Long.toHexString(get_cnt())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [val=0x"+Long.toHexString(get_val())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cnt
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cnt' is signed (false).
     */
    public static boolean isSigned_cnt() {
        return false;
    }

    /**
     * Return whether the field 'cnt' is an array (false).
     */
    public static boolean isArray_cnt() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cnt'
     */
    public static int offset_cnt() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cnt'
     */
    public static int offsetBits_cnt() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'cnt'
     */
    public short get_cnt() {
        return (short)getUIntBEElement(offsetBits_cnt(), 8);
    }

    /**
     * Set the value of the field 'cnt'
     */
    public void set_cnt(short value) {
        setUIntBEElement(offsetBits_cnt(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'cnt'
     */
    public static int size_cnt() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cnt'
     */
    public static int sizeBits_cnt() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: val
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'val' is signed (false).
     */
    public static boolean isSigned_val() {
        return false;
    }

    /**
     * Return whether the field 'val' is an array (false).
     */
    public static boolean isArray_val() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'val'
     */
    public static int offset_val() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'val'
     */
    public static int offsetBits_val() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'val'
     */
    public int get_val() {
        return (int)getUIntBEElement(offsetBits_val(), 16);
    }

    /**
     * Set the value of the field 'val'
     */
    public void set_val(int value) {
        setUIntBEElement(offsetBits_val(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'val'
     */
    public static int size_val() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'val'
     */
    public static int sizeBits_val() {
        return 16;
    }

}
